// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_Home.h"
#include "ui_Water.h"
#include "ui_Settings.h"
#include "ui_WifiSet.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * scroll_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_back_png);    // assets/back.png
LV_IMG_DECLARE(ui_img_1845835166);    // assets/temperature-control-64.png
LV_IMG_DECLARE(ui_img_197579651);    // assets/humidity-64.png
LV_IMG_DECLARE(ui_img_1156566852);    // assets/management-service.png
LV_IMG_DECLARE(ui_img_376556310);    // assets/no-wifi.png
LV_IMG_DECLARE(ui_img_wifi_png);    // assets/wifi.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
