// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_HOME_H
#define UI_HOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Home
extern void ui_Home_screen_init(void);
extern void ui_Home_screen_destroy(void);
extern lv_obj_t * ui_Home;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_ImgButton6;
extern void ui_event_ImgButton7(lv_event_t * e);
extern lv_obj_t * ui_ImgButton7;
extern void ui_event_ImgButton8(lv_event_t * e);
extern lv_obj_t * ui_ImgButton8;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_Temp;
extern lv_obj_t * ui_tempHome;
extern lv_obj_t * ui_Hum;
extern lv_obj_t * ui_HumHome;
extern lv_obj_t * ui_Press;
extern lv_obj_t * ui_pressHome;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Home;
extern lv_obj_t * uic_tempHome;
extern lv_obj_t * uic_HumHome;
extern lv_obj_t * uic_pressHome;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

