// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_pressHome;
lv_obj_t * uic_HumHome;
lv_obj_t * uic_tempHome;
lv_obj_t * uic_Home;
lv_obj_t * ui_Home = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_ImgButton6 = NULL;
lv_obj_t * ui_ImgButton7 = NULL;
lv_obj_t * ui_ImgButton8 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_TabView1 = NULL;
lv_obj_t * ui_Temp = NULL;
lv_obj_t * ui_tempHome = NULL;
lv_obj_t * ui_Hum = NULL;
lv_obj_t * ui_HumHome = NULL;
lv_obj_t * ui_Press = NULL;
lv_obj_t * ui_pressHome = NULL;
// event funtions
void ui_event_ImgButton7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Water, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Water_screen_init);
    }
}

void ui_event_ImgButton8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Settings_screen_init);
    }
}

// build funtions

void ui_Home_screen_init(void)
{
    ui_Home = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Home, &ui_img_back_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Home);
    lv_obj_set_width(ui_Panel1, 80);
    lv_obj_set_height(ui_Panel1, 240);
    lv_obj_set_x(ui_Panel1, -125);
    lv_obj_set_y(ui_Panel1, 0);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton6 = lv_imagebutton_create(ui_Panel1);
    lv_imagebutton_set_src(ui_ImgButton6, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_1845835166, NULL);
    lv_imagebutton_set_src(ui_ImgButton6, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_1845835166, NULL);
    lv_obj_set_width(ui_ImgButton6, 64);
    lv_obj_set_height(ui_ImgButton6, 64);
    lv_obj_set_x(ui_ImgButton6, 0);
    lv_obj_set_y(ui_ImgButton6, 50);
    lv_obj_set_align(ui_ImgButton6, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_ImgButton6, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ImgButton6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ImgButton6, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ImgButton6, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_ImgButton6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_ImgButton6, 200, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_blend_mode(ui_ImgButton6, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_opa(ui_ImgButton6, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_image_recolor(ui_ImgButton6, lv_color_hex(0x5699FF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_image_recolor_opa(ui_ImgButton6, 50, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_ImgButton7 = lv_imagebutton_create(ui_Panel1);
    lv_imagebutton_set_src(ui_ImgButton7, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_197579651, NULL);
    lv_imagebutton_set_src(ui_ImgButton7, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_197579651, NULL);
    lv_obj_set_width(ui_ImgButton7, 64);
    lv_obj_set_height(ui_ImgButton7, 64);
    lv_obj_set_x(ui_ImgButton7, 0);
    lv_obj_set_y(ui_ImgButton7, -50);
    lv_obj_set_align(ui_ImgButton7, LV_ALIGN_CENTER);
    lv_obj_set_style_blend_mode(ui_ImgButton7, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_opa(ui_ImgButton7, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_image_recolor(ui_ImgButton7, lv_color_hex(0x5699FF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_image_recolor_opa(ui_ImgButton7, 50, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_image_recolor(ui_ImgButton7, lv_color_hex(0x000000),
                                   LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);
    lv_obj_set_style_image_recolor_opa(ui_ImgButton7, 100, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);

    ui_ImgButton8 = lv_imagebutton_create(ui_Panel1);
    lv_imagebutton_set_src(ui_ImgButton8, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_1156566852, NULL);
    lv_imagebutton_set_src(ui_ImgButton8, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_1156566852, NULL);
    lv_obj_set_width(ui_ImgButton8, 64);
    lv_obj_set_height(ui_ImgButton8, 64);
    lv_obj_set_x(ui_ImgButton8, -125);
    lv_obj_set_y(ui_ImgButton8, 69);
    lv_obj_set_align(ui_ImgButton8, LV_ALIGN_CENTER);
    lv_obj_set_style_blend_mode(ui_ImgButton8, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_opa(ui_ImgButton8, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Panel2 = lv_obj_create(ui_Home);
    lv_obj_set_width(ui_Panel2, 220);
    lv_obj_set_height(ui_Panel2, 220);
    lv_obj_set_x(ui_Panel2, 40);
    lv_obj_set_y(ui_Panel2, 0);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 0);
    lv_obj_set_y(ui_Label1, -75);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Home");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabView1 = lv_tabview_create(ui_Panel2);
    lv_tabview_set_tab_bar_position(ui_TabView1, LV_DIR_BOTTOM);
    lv_tabview_set_tab_bar_size(ui_TabView1, 30);
    lv_obj_set_width(ui_TabView1, 220);
    lv_obj_set_height(ui_TabView1, 175);
    lv_obj_set_x(ui_TabView1, 0);
    lv_obj_set_y(ui_TabView1, 19);
    lv_obj_set_align(ui_TabView1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TabView1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TabView1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabView1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(lv_tabview_get_tab_bar(ui_TabView1), 5,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_tabview_get_tab_bar(ui_TabView1), lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_bar(ui_TabView1), 100,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temp = lv_tabview_add_tab(ui_TabView1, "Temp");

    ui_tempHome = lv_label_create(ui_Temp);
    lv_obj_set_width(ui_tempHome, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempHome, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_tempHome, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempHome, "%NaN");
    lv_obj_set_style_text_font(ui_tempHome, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Hum = lv_tabview_add_tab(ui_TabView1, "Hum");

    ui_HumHome = lv_label_create(ui_Hum);
    lv_obj_set_width(ui_HumHome, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumHome, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HumHome, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumHome, "%NaN");
    lv_obj_set_style_text_font(ui_HumHome, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Press = lv_tabview_add_tab(ui_TabView1, "Press");

    ui_pressHome = lv_label_create(ui_Press);
    lv_obj_set_width(ui_pressHome, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pressHome, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_pressHome, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pressHome, "%NaN");
    lv_obj_set_style_text_font(ui_pressHome, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ImgButton7, ui_event_ImgButton7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton8, ui_event_ImgButton8, LV_EVENT_ALL, NULL);
    uic_Home = ui_Home;
    uic_tempHome = ui_tempHome;
    uic_HumHome = ui_HumHome;
    uic_pressHome = ui_pressHome;

}

void ui_Home_screen_destroy(void)
{
    if(ui_Home) lv_obj_del(ui_Home);

    // NULL screen variables
    uic_Home = NULL;
    ui_Home = NULL;
    ui_Panel1 = NULL;
    ui_ImgButton6 = NULL;
    ui_ImgButton7 = NULL;
    ui_ImgButton8 = NULL;
    ui_Panel2 = NULL;
    ui_Label1 = NULL;
    ui_TabView1 = NULL;
    ui_Temp = NULL;
    uic_tempHome = NULL;
    ui_tempHome = NULL;
    ui_Hum = NULL;
    uic_HumHome = NULL;
    ui_HumHome = NULL;
    ui_Press = NULL;
    uic_pressHome = NULL;
    ui_pressHome = NULL;

}
