// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_SETTINGS_H
#define UI_SETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Settings
extern void ui_Settings_screen_init(void);
extern void ui_Settings_screen_destroy(void);
extern lv_obj_t * ui_Settings;
extern lv_obj_t * ui_Panel5;
extern void ui_event_ImgButton3(lv_event_t * e);
extern lv_obj_t * ui_ImgButton3;
extern void ui_event_ImgButton5(lv_event_t * e);
extern lv_obj_t * ui_ImgButton5;
extern lv_obj_t * ui_ImgButton9;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_TabView2;
extern lv_obj_t * ui_set1;
extern lv_obj_t * ui_uiwifiIcon;
extern lv_obj_t * ui_WifiMode;
extern void ui_event_setwifi(lv_event_t * e);
extern lv_obj_t * ui_setwifi;
extern lv_obj_t * ui_Label5;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Settings;
extern lv_obj_t * uic_set1;
extern lv_obj_t * uic_uiwifiIcon;
extern lv_obj_t * uic_WifiMode;
extern lv_obj_t * uic_setwifi;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

