// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_setwifi;
lv_obj_t * uic_WifiMode;
lv_obj_t * uic_uiwifiIcon;
lv_obj_t * uic_set1;
lv_obj_t * uic_Settings;
lv_obj_t * ui_Settings = NULL;
lv_obj_t * ui_Panel5 = NULL;
lv_obj_t * ui_ImgButton3 = NULL;
lv_obj_t * ui_ImgButton5 = NULL;
lv_obj_t * ui_ImgButton9 = NULL;
lv_obj_t * ui_Panel6 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_TabView2 = NULL;
lv_obj_t * ui_set1 = NULL;
lv_obj_t * ui_uiwifiIcon = NULL;
lv_obj_t * ui_WifiMode = NULL;
lv_obj_t * ui_setwifi = NULL;
lv_obj_t * ui_Label5 = NULL;
// event funtions
void ui_event_ImgButton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Home_screen_init);
    }
}

void ui_event_ImgButton5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Water, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Water_screen_init);
    }
}

void ui_event_setwifi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WifiSet, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_WifiSet_screen_init);
    }
}

// build funtions

void ui_Settings_screen_init(void)
{
    ui_Settings = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Settings, &ui_img_back_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_Settings);
    lv_obj_set_width(ui_Panel5, 80);
    lv_obj_set_height(ui_Panel5, 240);
    lv_obj_set_x(ui_Panel5, -125);
    lv_obj_set_y(ui_Panel5, 0);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel5, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_Panel5, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton3 = lv_imagebutton_create(ui_Panel5);
    lv_imagebutton_set_src(ui_ImgButton3, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_1845835166, NULL);
    lv_imagebutton_set_src(ui_ImgButton3, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_1845835166, NULL);
    lv_obj_set_width(ui_ImgButton3, 64);
    lv_obj_set_height(ui_ImgButton3, 64);
    lv_obj_set_x(ui_ImgButton3, 0);
    lv_obj_set_y(ui_ImgButton3, 50);
    lv_obj_set_align(ui_ImgButton3, LV_ALIGN_CENTER);
    lv_obj_set_style_blend_mode(ui_ImgButton3, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_opa(ui_ImgButton3, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_image_recolor(ui_ImgButton3, lv_color_hex(0x5699FF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_image_recolor_opa(ui_ImgButton3, 50, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_ImgButton5 = lv_imagebutton_create(ui_Panel5);
    lv_imagebutton_set_src(ui_ImgButton5, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_197579651, NULL);
    lv_imagebutton_set_src(ui_ImgButton5, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_197579651, NULL);
    lv_obj_set_width(ui_ImgButton5, 64);
    lv_obj_set_height(ui_ImgButton5, 64);
    lv_obj_set_x(ui_ImgButton5, 0);
    lv_obj_set_y(ui_ImgButton5, -50);
    lv_obj_set_align(ui_ImgButton5, LV_ALIGN_CENTER);
    lv_obj_set_style_blend_mode(ui_ImgButton5, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_ImgButton5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor(ui_ImgButton5, lv_color_hex(0x5699FF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_image_recolor_opa(ui_ImgButton5, 50, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_image_recolor(ui_ImgButton5, lv_color_hex(0x000000),
                                   LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);
    lv_obj_set_style_image_recolor_opa(ui_ImgButton5, 100, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);

    ui_ImgButton9 = lv_imagebutton_create(ui_Panel5);
    lv_imagebutton_set_src(ui_ImgButton9, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_1156566852, NULL);
    lv_imagebutton_set_src(ui_ImgButton9, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_1156566852, NULL);
    lv_obj_set_width(ui_ImgButton9, 64);
    lv_obj_set_height(ui_ImgButton9, 64);
    lv_obj_set_x(ui_ImgButton9, -125);
    lv_obj_set_y(ui_ImgButton9, 69);
    lv_obj_set_align(ui_ImgButton9, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_ImgButton9, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ImgButton9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ImgButton9, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_ImgButton9, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_ImgButton9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel6 = lv_obj_create(ui_Settings);
    lv_obj_set_width(ui_Panel6, 220);
    lv_obj_set_height(ui_Panel6, 220);
    lv_obj_set_x(ui_Panel6, 40);
    lv_obj_set_y(ui_Panel6, 0);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 0);
    lv_obj_set_y(ui_Label3, -75);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Settings");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabView2 = lv_tabview_create(ui_Panel6);
    lv_tabview_set_tab_bar_position(ui_TabView2, LV_DIR_BOTTOM);
    lv_tabview_set_tab_bar_size(ui_TabView2, 30);
    lv_obj_set_width(ui_TabView2, 220);
    lv_obj_set_height(ui_TabView2, 175);
    lv_obj_set_x(ui_TabView2, 0);
    lv_obj_set_y(ui_TabView2, 19);
    lv_obj_set_align(ui_TabView2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_TabView2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TabView2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TabView2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabView2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(lv_tabview_get_tab_bar(ui_TabView2), 5,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_tabview_get_tab_bar(ui_TabView2), lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_bar(ui_TabView2), 100,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_set1 = lv_tabview_add_tab(ui_TabView2, "WiFi");

    ui_uiwifiIcon = lv_image_create(ui_set1);
    lv_image_set_src(ui_uiwifiIcon, &ui_img_376556310);
    lv_obj_set_width(ui_uiwifiIcon, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_uiwifiIcon, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_uiwifiIcon, -60);
    lv_obj_set_y(ui_uiwifiIcon, 0);
    lv_obj_set_align(ui_uiwifiIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_uiwifiIcon, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_uiwifiIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiMode = lv_label_create(ui_set1);
    lv_obj_set_width(ui_WifiMode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiMode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiMode, 0);
    lv_obj_set_y(ui_WifiMode, 50);
    lv_obj_set_align(ui_WifiMode, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WifiMode, "%mode%");

    ui_setwifi = lv_button_create(ui_Settings);
    lv_obj_set_width(ui_setwifi, 100);
    lv_obj_set_height(ui_setwifi, 32);
    lv_obj_set_x(ui_setwifi, 76);
    lv_obj_set_y(ui_setwifi, 0);
    lv_obj_set_align(ui_setwifi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_setwifi, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_setwifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_setwifi, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_setwifi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setwifi, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_setwifi);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Setup WiFi");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ImgButton3, ui_event_ImgButton3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton5, ui_event_ImgButton5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_setwifi, ui_event_setwifi, LV_EVENT_ALL, NULL);
    uic_Settings = ui_Settings;
    uic_set1 = ui_set1;
    uic_uiwifiIcon = ui_uiwifiIcon;
    uic_WifiMode = ui_WifiMode;
    uic_setwifi = ui_setwifi;

}

void ui_Settings_screen_destroy(void)
{
    if(ui_Settings) lv_obj_del(ui_Settings);

    // NULL screen variables
    uic_Settings = NULL;
    ui_Settings = NULL;
    ui_Panel5 = NULL;
    ui_ImgButton3 = NULL;
    ui_ImgButton5 = NULL;
    ui_ImgButton9 = NULL;
    ui_Panel6 = NULL;
    ui_Label3 = NULL;
    ui_TabView2 = NULL;
    uic_set1 = NULL;
    ui_set1 = NULL;
    uic_uiwifiIcon = NULL;
    ui_uiwifiIcon = NULL;
    uic_WifiMode = NULL;
    ui_WifiMode = NULL;
    uic_setwifi = NULL;
    ui_setwifi = NULL;
    ui_Label5 = NULL;

}
