// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_BulbTemp;
lv_obj_t * uic_CWUTemp;
lv_obj_t * uic_Water;
lv_obj_t * ui_Water = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_ImgButton1 = NULL;
lv_obj_t * ui_ImgButton2 = NULL;
lv_obj_t * ui_ImgButton4 = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_TabView3 = NULL;
lv_obj_t * ui_CWU = NULL;
lv_obj_t * ui_CWUTemp = NULL;
lv_obj_t * ui_Bulb = NULL;
lv_obj_t * ui_BulbTemp = NULL;
// event funtions
void ui_event_ImgButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Home_screen_init);
    }
}

void ui_event_ImgButton4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Settings_screen_init);
    }
}

// build funtions

void ui_Water_screen_init(void)
{
    ui_Water = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Water, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Water, &ui_img_back_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Water);
    lv_obj_set_width(ui_Panel3, 80);
    lv_obj_set_height(ui_Panel3, 240);
    lv_obj_set_x(ui_Panel3, -125);
    lv_obj_set_y(ui_Panel3, 0);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton1 = lv_imagebutton_create(ui_Panel3);
    lv_imagebutton_set_src(ui_ImgButton1, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_1845835166, NULL);
    lv_imagebutton_set_src(ui_ImgButton1, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_1845835166, NULL);
    lv_obj_set_width(ui_ImgButton1, 64);
    lv_obj_set_height(ui_ImgButton1, 64);
    lv_obj_set_x(ui_ImgButton1, 0);
    lv_obj_set_y(ui_ImgButton1, 50);
    lv_obj_set_align(ui_ImgButton1, LV_ALIGN_CENTER);
    lv_obj_set_style_blend_mode(ui_ImgButton1, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_opa(ui_ImgButton1, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_image_recolor(ui_ImgButton1, lv_color_hex(0x5699FF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_image_recolor_opa(ui_ImgButton1, 50, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_ImgButton2 = lv_imagebutton_create(ui_Panel3);
    lv_imagebutton_set_src(ui_ImgButton2, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_197579651, NULL);
    lv_imagebutton_set_src(ui_ImgButton2, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_197579651, NULL);
    lv_obj_set_width(ui_ImgButton2, 64);
    lv_obj_set_height(ui_ImgButton2, 64);
    lv_obj_set_x(ui_ImgButton2, 0);
    lv_obj_set_y(ui_ImgButton2, -50);
    lv_obj_set_align(ui_ImgButton2, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_ImgButton2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ImgButton2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ImgButton2, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_ImgButton2, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_ImgButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor(ui_ImgButton2, lv_color_hex(0x5699FF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_image_recolor_opa(ui_ImgButton2, 50, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_image_recolor(ui_ImgButton2, lv_color_hex(0x000000),
                                   LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);
    lv_obj_set_style_image_recolor_opa(ui_ImgButton2, 100, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);

    ui_ImgButton4 = lv_imagebutton_create(ui_Panel3);
    lv_imagebutton_set_src(ui_ImgButton4, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_1156566852, NULL);
    lv_imagebutton_set_src(ui_ImgButton4, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_1156566852, NULL);
    lv_obj_set_width(ui_ImgButton4, 64);
    lv_obj_set_height(ui_ImgButton4, 64);
    lv_obj_set_x(ui_ImgButton4, -125);
    lv_obj_set_y(ui_ImgButton4, 69);
    lv_obj_set_align(ui_ImgButton4, LV_ALIGN_CENTER);
    lv_obj_set_style_blend_mode(ui_ImgButton4, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_opa(ui_ImgButton4, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Panel4 = lv_obj_create(ui_Water);
    lv_obj_set_width(ui_Panel4, 220);
    lv_obj_set_height(ui_Panel4, 220);
    lv_obj_set_x(ui_Panel4, 40);
    lv_obj_set_y(ui_Panel4, 0);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 0);
    lv_obj_set_y(ui_Label2, -75);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Water");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabView3 = lv_tabview_create(ui_Panel4);
    lv_tabview_set_tab_bar_position(ui_TabView3, LV_DIR_BOTTOM);
    lv_tabview_set_tab_bar_size(ui_TabView3, 30);
    lv_obj_set_width(ui_TabView3, 220);
    lv_obj_set_height(ui_TabView3, 175);
    lv_obj_set_x(ui_TabView3, 0);
    lv_obj_set_y(ui_TabView3, 19);
    lv_obj_set_align(ui_TabView3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_TabView3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TabView3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TabView3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabView3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(lv_tabview_get_tab_bar(ui_TabView3), 5,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_tabview_get_tab_bar(ui_TabView3), lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_bar(ui_TabView3), 100,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CWU = lv_tabview_add_tab(ui_TabView3, "CWU");

    ui_CWUTemp = lv_label_create(ui_CWU);
    lv_obj_set_width(ui_CWUTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CWUTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CWUTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CWUTemp, "%NaN");
    lv_obj_set_style_text_font(ui_CWUTemp, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bulb = lv_tabview_add_tab(ui_TabView3, "Bulbulator");

    ui_BulbTemp = lv_label_create(ui_Bulb);
    lv_obj_set_width(ui_BulbTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BulbTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BulbTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BulbTemp, "%NaN");
    lv_obj_set_style_text_font(ui_BulbTemp, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ImgButton1, ui_event_ImgButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton4, ui_event_ImgButton4, LV_EVENT_ALL, NULL);
    uic_Water = ui_Water;
    uic_CWUTemp = ui_CWUTemp;
    uic_BulbTemp = ui_BulbTemp;

}

void ui_Water_screen_destroy(void)
{
    if(ui_Water) lv_obj_del(ui_Water);

    // NULL screen variables
    uic_Water = NULL;
    ui_Water = NULL;
    ui_Panel3 = NULL;
    ui_ImgButton1 = NULL;
    ui_ImgButton2 = NULL;
    ui_ImgButton4 = NULL;
    ui_Panel4 = NULL;
    ui_Label2 = NULL;
    ui_TabView3 = NULL;
    ui_CWU = NULL;
    uic_CWUTemp = NULL;
    ui_CWUTemp = NULL;
    ui_Bulb = NULL;
    uic_BulbTemp = NULL;
    ui_BulbTemp = NULL;

}
