// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_WIFISET_H
#define UI_WIFISET_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_WifiSet
extern void ui_WifiSet_screen_init(void);
extern void ui_WifiSet_screen_destroy(void);
extern lv_obj_t * ui_WifiSet;
extern void ui_event_Keyboard1(lv_event_t * e);
extern lv_obj_t * ui_Keyboard1;
extern void ui_event_SSID(lv_event_t * e);
extern lv_obj_t * ui_SSID;
extern void ui_event_PASS(lv_event_t * e);
extern lv_obj_t * ui_PASS;
extern void ui_event_done(lv_event_t * e);
extern lv_obj_t * ui_done;
extern lv_obj_t * ui_Label4;
// CUSTOM VARIABLES
extern lv_obj_t * uic_WifiSet;
extern lv_obj_t * uic_SSID;
extern lv_obj_t * uic_PASS;
extern lv_obj_t * uic_done;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

