// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_done;
lv_obj_t * uic_PASS;
lv_obj_t * uic_SSID;
lv_obj_t * uic_WifiSet;
lv_obj_t * ui_WifiSet = NULL;
lv_obj_t * ui_Keyboard1 = NULL;
lv_obj_t * ui_SSID = NULL;
lv_obj_t * ui_PASS = NULL;
lv_obj_t * ui_done = NULL;
lv_obj_t * ui_Label4 = NULL;
// event funtions
void ui_event_Keyboard1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_ENTER) {
        InitWifi(e);
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Settings_screen_init);
    }
}

void ui_event_SSID(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_SSID);
    }
}

void ui_event_PASS(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_PASS);
    }
}

void ui_event_done(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        InitWifi(e);
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Settings_screen_init);
    }
}

// build funtions

void ui_WifiSet_screen_init(void)
{
    ui_WifiSet = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_WifiSet, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_WifiSet, &ui_img_back_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_WifiSet);
    lv_obj_set_width(ui_Keyboard1, 320);
    lv_obj_set_height(ui_Keyboard1, 120);
    lv_obj_set_x(ui_Keyboard1, 0);
    lv_obj_set_y(ui_Keyboard1, 60);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Keyboard1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Keyboard1, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SSID = lv_textarea_create(ui_WifiSet);
    lv_obj_set_width(ui_SSID, 140);
    lv_obj_set_height(ui_SSID, 35);
    lv_obj_set_x(ui_SSID, -80);
    lv_obj_set_y(ui_SSID, -80);
    lv_obj_set_align(ui_SSID, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_SSID, "SSID");

    ui_PASS = lv_textarea_create(ui_WifiSet);
    lv_obj_set_width(ui_PASS, 140);
    lv_obj_set_height(ui_PASS, 35);
    lv_obj_set_x(ui_PASS, 80);
    lv_obj_set_y(ui_PASS, -80);
    lv_obj_set_align(ui_PASS, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_PASS, "PASSWORD");

    ui_done = lv_button_create(ui_WifiSet);
    lv_obj_set_width(ui_done, 100);
    lv_obj_set_height(ui_done, 31);
    lv_obj_set_x(ui_done, 0);
    lv_obj_set_y(ui_done, -30);
    lv_obj_set_align(ui_done, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_done, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_done, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_done, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_done, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_done, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_done);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Done");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_keyboard_set_textarea(ui_Keyboard1, ui_SSID);
    lv_obj_add_event_cb(ui_Keyboard1, ui_event_Keyboard1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SSID, ui_event_SSID, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PASS, ui_event_PASS, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_done, ui_event_done, LV_EVENT_ALL, NULL);
    uic_WifiSet = ui_WifiSet;
    uic_SSID = ui_SSID;
    uic_PASS = ui_PASS;
    uic_done = ui_done;

}

void ui_WifiSet_screen_destroy(void)
{
    if(ui_WifiSet) lv_obj_del(ui_WifiSet);

    // NULL screen variables
    uic_WifiSet = NULL;
    ui_WifiSet = NULL;
    ui_Keyboard1 = NULL;
    uic_SSID = NULL;
    ui_SSID = NULL;
    uic_PASS = NULL;
    ui_PASS = NULL;
    uic_done = NULL;
    ui_done = NULL;
    ui_Label4 = NULL;

}
