// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_WATER_H
#define UI_WATER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Water
extern void ui_Water_screen_init(void);
extern void ui_Water_screen_destroy(void);
extern lv_obj_t * ui_Water;
extern lv_obj_t * ui_Panel3;
extern void ui_event_ImgButton1(lv_event_t * e);
extern lv_obj_t * ui_ImgButton1;
extern lv_obj_t * ui_ImgButton2;
extern void ui_event_ImgButton4(lv_event_t * e);
extern lv_obj_t * ui_ImgButton4;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_TabView3;
extern lv_obj_t * ui_CWU;
extern lv_obj_t * ui_CWUTemp;
extern lv_obj_t * ui_Bulb;
extern lv_obj_t * ui_BulbTemp;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Water;
extern lv_obj_t * uic_CWUTemp;
extern lv_obj_t * uic_BulbTemp;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

